# Generated by Django 4.0.1 on 2022-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('instagram_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
            ],
        ),
    ]
