# Generated by Django 4.0.1 on 2022-02-14 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('interest', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=128)),
                ('message', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 6, 10, 205837))),
                ('car_id', models.IntegerField()),
                ('car_title', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
