# Generated by Django 4.0 on 2022-01-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='loacation',
            new_name='location',
        ),
    ]
